# NumPy 배열 생성 및 연산 문제 풀기: 모든 미니퀘스트 수행

## 차원 -미니퀘스트

<aside>
👉 다음 NumPy 배열의 차원 수를 출력하는 코드를 작성하세요.

```python
import numpy as np
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
```

</aside>

In [2]:
import numpy as np

array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(array.ndim)

3


<aside>
👉 1차원 배열 `[10, 20, 30, 40, 50, 60]`을 2차원 배열로 변환하여 (2, 3) 형태로 출력하는 코드를 작성하세요.

</aside>

In [3]:
import numpy as np

array = np.array([10, 20, 30, 40, 50,60])

rehaped_array = array.reshape(2, 3)

print(rehaped_array)

[[10 20 30]
 [40 50 60]]


<aside>
👉 다음 1차원 배열에 새로운 차원을 추가하여 2차원 배열로 변환하고, 최종 배열의 차원 수를 출력하세요.

- `newaxis`를 사용하여 배열의 차원을 추가하고, 새로운 차원에서의 배열 모양을 확인한 후 최종 차원 수를 출력하세요.

```python
import numpy as np
array = np.array([7, 14, 21])
```

</aside>

In [4]:
import numpy as np
array = np.array([7, 14, 21])

col_axis = array[:, np.newaxis]
row_axis = array[np.newaxis, :]

print(col_axis)
print(col_axis.shape)
print(col_axis.ndim)


[[ 7]
 [14]
 [21]]
(3, 1)
2


In [5]:
print(row_axis)
print(row_axis.shape)
print(row_axis.ndim)


[[ 7 14 21]]
(1, 3)
2


## Shape - 미니퀘스트

### 1번 퀘스트

<aside>
👉 주어진 2차원 NumPy 배열의 형태(Shape)를 출력하는 코드를 작성하세요.

```python
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
```
</aside>

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])

print(array.shape)

(2, 3)


### 2번 퀘스트

<aside>
👉 1차원 배열 `[10, 20, 30, 40, 50, 60]`을 (2, 3) 형태로 변경한 후, 새로운 배열의 형태를 출력하는 코드를 작성하세요.

</aside>

In [10]:
import numpy as np

array = np.array([[10, 20, 30, 40, 50, 60]])

reshape_array = array.reshape(2,3)

print(reshape_array.shape)

(2, 3)


### 3번 퀘스트

<aside>
👉 다음 3차원 배열의 형태를 변경하여 (3, 2, 2) 형태로 조정하고, 최종 배열의 형태를 출력하는 코드를 작성하세요.

```python
import numpy as np
array = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])
```

</aside>

In [2]:
import numpy as np

array = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

reshaped_array = array.reshape(3, 2, 2)

print(reshaped_array)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


## 데이터 타입 - 미니퀘스트

### 1번 퀘스트

<aside>
👉 아래의 NumPy 배열의 데이터 타입을 확인하는 코드를 작성하세요.

```python
import numpy as np
array = np.array([10, 20, 30])
```

</aside>

In [11]:
import numpy as np
array = np.array([10, 20, 30])

print(array.dtype)

int64


### 2번 퀘스트

<aside>
👉 정수형 배열 `[1, 2, 3]`을 부동소수점형 배열로 변환하고, 변환된 배열의 데이터 타입을 출력하는 코드를 작성하세요.

</aside>

In [ ]:
import numpy as np

array = np.array([1, 2, 3], dtype = np.float64)

print(array.dtype)


float64


### 3번 퀘스트

<aside>
👉 NumPy 배열 `[100, 200, 300]`을 `uint8`로 변환한 후, 메모리 사용량(바이트)을 출력하는 코드를 작성하세요.

</aside>

In [15]:
import numpy as np

array = np.array([100, 200, 300], dtype = np.uint8)

print(array.nbytes)


3


/var/folders/52/bqgpzt9j7bxb3qp5wx2jchg00000gn/T/ipykernel_50461/840976014.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  array = np.array([100, 200, 300], dtype = np.uint8)


해당 오류는 최신 NumPy 환경에서 범위를 벗어나는 정수 데이터를 배열 생성과 동시에 특정 정수 타입(`dtype`)으로 강제 지정할 때 아래와 같은 경고 메시지가 발생한다고 합니다 따라서 아래와 같은 코드로 변경했습니다.

In [ ]:
import numpy as np

raw_array = [100, 200, 300]

array = np.clip(raw_array, 0, 255).astype(np.uint8) # uin8의 표현 범위가 0~255이기 때문에 범위를 클리핑 후 메모리 사용량 출력

print(array.nbytes)

3


## 인덱싱 - 미니퀘스트

### 1번 퀘스트

<aside>
👉 주어진 1차원 배열에서 첫 번째 요소와 마지막 요소를 출력하는 코드를 작성하세요.

```python
import numpy as np
array = np.array([10, 20, 30, 40, 50])
```

</aside>

In [ ]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])

print(array[0])
print(array[-1]) # 배열 안의 개수를 몰라도 마지막 요소 출력


10
50


### 2번 퀘스트

<aside>
👉 주어진 2차원 배열에서 첫 번째 열과 두 번째 행을 출력하는 코드를 작성하세요.

```python
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
```

</aside>

In [22]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix[:, 0])
print(matrix[1, :])

[1 4 7]
[4 5 6]


### 3번 퀘스트

<aside>
👉 주어진 배열에서 10보다 큰 요소들만 선택하고, 해당 요소들의 인덱스를 출력하는 코드를 작성하세요.

```python
import numpy as np
array = np.array([5, 15, 8, 20, 3, 12])
```

</aside>

In [24]:
import numpy as np
array = np.array([5, 15, 8, 20, 3, 12])

result = array[array > 10]

result_index = np.where(array > 10)[0]

print(result)
print(result_index)



[15 20 12]
[1 3 5]


## 연산 - 미니퀘스트

### 1번 퀘스트

<aside>
👉 주어진 NumPy 배열에서 요소별(Element-wise) 덧셈을 수행하는 코드를 작성하세요.

```python
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
```

</aside>

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


### 2번 퀘스트

<aside>
👉 다음 NumPy 배열에서 브로드캐스팅을 활용하여 각 행에 `[1, 2, 3]`을 더하는 코드를 작성하세요.

```python
import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])
```

</aside>

In [28]:
import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])

print(matrix + [1, 2, 3])
print(vector + [1, 2, 3])

print(matrix + vector) #문제의 의도가 이건가요..?

[[11 22 33]
 [41 52 63]]
[2 4 6]
[[11 22 33]
 [41 52 63]]


### 3번 퀘스트

<aside>
👉 주어진 2차원 NumPy 배열에 대해, 축(axis)을 기준으로 최댓값을 구하고 최종 배열의 차원을 출력하는 코드를 작성하세요.

```python
import numpy as np
array = np.array([[3, 7, 2], [8, 4, 6]])
```

</aside>

In [31]:
import numpy as np

array = np.array([[3, 7, 2], [8, 4, 6]])

max_array_col = np.max(array, axis = 0)
max_array_row = np.max(array, axis = 1)

print(max_array_col)
print(max_array_row)

[8 7 6]
[7 8]


## 유니버설 함수 - 미니퀘스트

### 1번 퀘스트

<aside>
👉 배열 `[1, 2, 3, 4]`에 대해 NumPy의 유니버설 함수를 사용하여 모든 요소를 제곱한 결과를 출력하는 코드를 작성하세요.

</aside>

In [ ]:
import numpy as np

array = ([1, 2, 3, 4])

print(np.power(array, 2))

[ 1  8 27 64]


### 2번 퀘스트

<aside>
👉 다음 두 배열의 요소별 합을 계산하고, 결과를 새로운 배열이 아닌 기존 배열에 저장하는 코드를 작성하세요.

```python
array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])
```

</aside>

In [41]:
import numpy as np

array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])

np.add(array1, array2, out = array1)

print(array1)




[11 22 33]


### 3번 퀘스트

<aside>
👉 다음 배열에 대해 NumPy 유니버설 함수를 사용하여 요소별로 자연로그(log)를 계산하고, 특정 조건(`log 값 > 1`)을 만족하는 요소만 출력하는 코드를 작성하세요.

```python
array = np.array([1, np.e, 10, 100])
```

</aside>

In [ ]:
import numpy as np

array = np.array([1, np.e, 10, 100])

log_array = np.log(array)

conditions = log_array > 1
filtered_array = log_array[conditions]

print(log_array)
print("만족하는 값:",filtered_array)


[0.         1.         2.30258509 4.60517019]
만족하는 값: [2.30258509 4.60517019]
